# Generated by Django 2.2.2 on 2021-05-26 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subthread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('topic', models.CharField(max_length=500)),
                ('mainthread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumapp.Mainthread')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=500)),
                ('subthread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumapp.Subthread')),
            ],
        ),
    ]
