# Generated by Django 2.2.2 on 2021-05-31 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0002_comment_subthread'),
    ]

    operations = [
        migrations.AddField(
            model_name='subthread',
            name='number_of_views',
            field=models.IntegerField(default=0),
        ),
    ]
