# Generated by Django 2.2.2 on 2021-05-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0003_subthread_number_of_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainthread',
            name='number_of_views',
            field=models.IntegerField(default=0),
        ),
    ]
