# Generated by Django 2.2.2 on 2021-06-05 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0006_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='subthread',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
