# Generated by Django 2.2.2 on 2021-06-05 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0007_auto_20210605_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='subthread',
            name='time',
            field=models.TimeField(default=datetime.time(12, 38, 54, 749777)),
        ),
    ]
