# Generated by Django 2.2.2 on 2021-06-05 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0008_subthread_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='number_of_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.TimeField(default=datetime.time(13, 4, 25, 880552)),
        ),
        migrations.AlterField(
            model_name='subthread',
            name='time',
            field=models.TimeField(default=datetime.time(13, 4, 25, 880552)),
        ),
    ]
